root: D:/tmp/network

network:
  itscyRoot: ${root}/itscy/upload/
  itscyExport: ${root}/itscy/export/
  firewallRoot: ${root}/firewall/

logging:
  file: ${root}/log/network.log

server:
  port: 443
  context-path: /network
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 123123
    key-alias: tomcat
    trust-store-type: PCKS12
